### ISSUE TITLE
Fix appveyor builds

### ISSUE THREAD

**Issue by mbrt** [mbrt/ruplicity#43]
Builds are failing for target `x86_64-pc-windows-msvc`. The build fails because `advapi32-sys` can't find `ws2_32.lib`.

See [this PR](https://github.com/libpnet/libpnet/pull/135/files) for a temporary fix, and [this rust-lang issue](https://github.com/rust-lang/rust/issues/30229) for the complete fix.

**Comment by vitaly-krugl** [comment]
@mbrt, sorry to disturb you. I am getting the same errors on appveyor using mingw toolchain in an open-source nupic.core build (https://ci.appveyor.com/project/vitaly-krugl/nupic-core/build/job/5rvqsrgoqryoer7n):

```
C:/Python27/share/mingwpy/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lws2_32.lib
C:/Python27/share/mingwpy/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lmswsock.lib
C:/Python27/share/mingwpy/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lrpcrt4.lib
```

The commit https://github.com/mbrt/ruplicity/commit/afc66cf7c5e361f806d0c8c4e65cb160cca82d05 appears to fix the same issue in your Visual Studio build. Do you know what I need to do to fix the similar issue in mingw builds?

Many thanks,
Vitaly

**Comment by mbrt** [comment]
My problem was about an issue Rust had (or has, I don't know if it is
fixed) in detecting the paths necessary to a proper link in particular
configuration AppVeyor workers has. So calling those batch would set the
PATH variable correctly. I don't know if it's the same issue for you. I
suggest you to ask in the IRC channel if someone else had the same issue,
or to copy the configuration from other crates supporting mingw.
Il 24/mar/2016 22:00, "vitaly-krugl" <notifications@github.com> ha scritto:

**Comment by vitaly-krugl** [comment]
Thanks @mbrt

**Comment by mbrt** [comment]
You're welcome!
Il 24/mar/2016 22:34, "vitaly-krugl" <notifications@github.com> ha scritto:
